### ISSUE TITLE
No way to use in Azure Pipelines YAML

### ISSUE THREAD

**Issue by ericchansen** [microsoft/botframework-cli#1071]
It's not easy to use the BF CLI in Azure Pipelines. It's hard to install globally (usually get errors), and it's hard to make use of if you only install it locally.

Please provide an example of installing and using the BF CLI in an Azure Pipelines YAML.

**Comment by tonyanziano** [comment]
@axelsrz / @munozemilio do either of you know of a way to do this or have a sample showing how to accomplish this?

**Comment by joshgummersall** [comment]
What kind of errors? Have you tried to install globally and enable caching to ensure that subsequent runs of a pipeline don't need to reinstall?

**Comment by munozemilio** [comment]
Hello @ericchansen. In the past I have used it like this:
```
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
  - task: NodeTool@0
    displayName: Use Node 13.x
    inputs:
      versionSpec: 13.x
  - task: CmdLine@2
    displayName: Set environment variable
    inputs:
      script: set BF_CLI_TELEMETRY = true
  - task: CmdLine@2
    displayName: install cli
    inputs:
      script: npm install -g @microsoft/botframework-cli
  - task: CmdLine@2
    displayName: Run config command
    inputs:
      script: bf
```

let me know if this works for you. Otherwise Im more than happy to work on improving the usage experience
